### ISSUE TITLE
Metafilter Scroll Tag issues with Firefox Quantum

### ISSUE THREAD

**Issue by jcushman** [mefiscripts/mefiscripts#11]
As [reported over on Metatalk](https://metatalk.metafilter.com/24621/Metafilter-Scroll-Tag-issues-on-FF-Quantum), sounds like Metafilter Scroll Tag has some issues with the latest Firefox:

"When I open a thread, I have to click on the timestamp on the first comment to get the little arrow in the left margin. But it doesn't follow me down the page with a downward arrow. If I click on the timestamp of another comment, I get the arrow in the left margin again, but that's it. Going back to a thread, there's no way to navigate back to the last read comment."

This is a Plutor script, and he's given permission to add all of those scripts to this repo. So if anyone wants to pick that up and add the script (with or without Quantum fixes) that would be a great first step.

**Comment by pronoiac** [comment]
I've [gotten it working](https://github.com/pronoiac/mefiscripts/blob/master/userscripts/scroll_tag.user.js) in Tampermonkey, though not in Greasemonkey.
