### ISSUE TITLE
Correct namespace for scripts?

### ISSUE THREAD

**Issue by jcushman** [mefiscripts/mefiscripts#3]
Does anyone know the correct namespace line for scripts? Like fuzzo.txt right now has

    // @namespace      https://userscripts-mirror.org/

There are some Google results suggesting that "[Scripts with the same namespace will run within the same context and access each others variables,](https://forum.tampermonkey.net/viewtopic.php?t=75)" which seems like it should be something more unique than userscripts-mirror.org, but I'm not sure what.

**Comment by emanuelfeld** [comment]
I just put my GitHub user page, i.e. https://github.com/emanuelfeld.

**Comment by emanuelfeld** [comment]
This is also closed, right?

**Comment by Samizdata** [comment]
It is being closed.
