### ISSUE TITLE
Update mefi deleted posts script

### ISSUE THREAD

**Issue by jcushman** [mefiscripts/mefiscripts#4]
There are some requests for an updated mefi deleted posts script -- I think for https, for Chrome compat, and for WebExtensions Greasemonkey in Firefox 57+.

Here's a BSD-licensed version that we could start from, if there isn't another more up-to-date: http://userscripts-mirror.org/scripts/show/809

(We haven't done issues yet -- how about if you want to take a crack at this, assign yourself?)

**Comment by rhizome** [comment]
I've been looking into this this morning. Is it important at all to have GM 3.x compatibility or a version that works with 3.x at all, or should it just jump to 4.x style?

The version you link appears to be newer (has some 4.x stuff) than the one on plutor.org

**Comment by jcushman** [comment]
Might depend how hard it is. But if supporting multiple platforms seems annoying, maybe kick out something that works in at least one browser, note any limitations in userscripts/README.md, and folks can file issues if they have another target in mind?

**Comment by davekaufman** [comment]
FWIW, plutor's script works for me with the classic theme, in Chrome and FF on Windows.  I recognize that I'm the oddball for remaining on classic...

**Comment by rf14** [comment]
I have a working version of this for Tampermonkey or old Greasemonkey (for Modern and Classic) - can try to post it this weekend.

**Comment by rf14** [comment]
@rhizome oops I just saw your PR #18 which has the same filename.  I can rename my file and try again.

**Comment by emanuelfeld** [comment]
This is closed, right?
