### ISSUE TITLE
Any place for full Chrome extensions?

### ISSUE THREAD

**Issue by jimkang** [mefiscripts/mefiscripts#5]
I have a Chrome extension that pulls comments from just your mutual contacts:

https://chrome.google.com/webstore/detail/decent-activity/phjbedoddmlcjddhgippapnfpbmmpimg

Source here:

https://github.com/jimkang/decent-activity

Is there anywhere I can put that in here?

**Comment by jcushman** [comment]
Good question! My hesitation is, if we host extensions here, does that imply that we've verified the same code is being served at the Chrome webstore, and that we can post new versions if people send in new code?

Basically, I'm not sure it makes sense for this group to post stuff to the Chrome webstore, and I'm not sure it makes sense for us to host code if we can't. 

Definitely open to other angles on this, though ...

**Comment by jimkang** [comment]
Ah, I was thinking maybe it could linked from a "related stuff" section on the README or something rather than actually hosted here.

**Comment by jcushman** [comment]
Oh, gotcha, great idea.

Does it make sense to link directly to extensions from the README, or to http://mefiwiki.com/wiki/More_Resources#Software_.26_Extensions and http://mefiwiki.com/wiki/Greasemonkey_Scripts_and_Plugins ? I'm +1 either way.

**Comment by andywillis** [comment]
Linking directly to extensions would be better imo.

**Comment by jimkang** [comment]
Looks like it's settled! Obvs, feel free to reopen if I'm wrong!

**Comment by andywillis** [comment]
@jimkang I was thinking more of a folder called Web Extensions with a single README listing the links, rather than a sub-heading hidden on the main page. What do you think?

**Comment by jimkang** [comment]
Sure, as long as it's discoverable, that works for me.

**Comment by andywillis** [comment]
I've got some extensions to add so I'll do a PR at some point.
