### ISSUE TITLE
Needs Updates: MefiQuote and EasyMeMail

### ISSUE THREAD

**Issue by Samizdata** [mefiscripts/mefiscripts#9]
I would offer to help, but I have made these two user-scripts non-functional messes trying to do so already.  I was SO pleased when I finally gave up on Brave to come back to Quantum, I would have my MeFiQuote script again, but, PSYCH!

Cheers, Bluefolk!

**Comment by Samizdata** [comment]
Oh, that's Plutor's quote script (will abandon it if there's something better - Sorry, Plutor!).  And that's my highest priority.  The EasyMeMail is a "Would be nice, but.."

**Comment by rf14** [comment]
@Samizdata I'll add a mefiquote script for FF Quantum within the next day or so.

**Comment by rf14** [comment]
@Samizdata here's the mefiquote file I have now: https://gist.github.com/rf14/50b8300c0a682d3a8c714f3b7f551be1

I'm still learning my way around git and am trying to figure out how best to do a new pull request without messing up anything else.  In the meantime, if you'd like, you can see if the above works for you (works for me in FF Quantum and Greasemonkey 4, should also work in FF/Tampermonkey) -- let me know if it doesn't.

**Comment by Samizdata** [comment]
Looks promising.  Although I am still a Classic weenie.  I will try Modern again though.

**Comment by Samizdata** [comment]
Looks shiny.  Guess I am running Modern for now.  Cheers!

**Comment by rf14** [comment]
@Samizdata - glad it works for you on Modern. Just submitted a pull request (PR #22).

I took a look at fixing mefiquote for Classic, and also looked at easymemail, but I think they're beyond my knowledge at this point.  Hopefully someone can look further...

**Comment by emanuelfeld** [comment]
I actually didn't realize MefiQuote existed before I made MefiReply, which is functionally mostly the same (especially now that I let people select the text they want quoted). No preferences pane in mine, though. It works in both Classic and Modern.

Can this issue be closed?

**Comment by Samizdata** [comment]
I will close this.
